### ISSUE TITLE
"Banned for using automated systems"

### ISSUE THREAD

**Issue by foryouto** [batdan/midjourney-php#9]
Keep getting banned from Midjourney for "using automated systems". Not sure how they can detect it, if you have any ideas let me know.

Thanks.

**Comment by foryouto** [comment]
Tried making the seed value more static (between 1-99) so it doesn't seem so random but still got banned after a week or so.

**Comment by batdan** [comment]
I never had a problem after 1 month of use generating 40 images per day.

The random value can only be between 0 and 3 because Midjourney only offers 4 images. Personally, I don't fill in this value and I let the class manage on its own to make a random choice.

I think the problem is more related to the content of the prompt than to the choice of the image.
